- hosts: localhost
  connection: local
  tasks:
    - name: Creating resource group
      azure_rm_resourcegroup:
        name: demo-rg
        location: Centralindia
      register: rg
    - debug:
        var: rg