- hosts: cassandra
  become: yes
  environment:
    sunbird_cassandra_host: "{{ groups['cassandra'][0] }}"
    sunbird_cassandra_port: 9042
    sunbird_cassandra_keyspace: "{{cassandra_keyspace_to_migrate}}"
    sunbird_cassandra_migration_location: "filesystem:migration-script/{{cassandra_keyspace_to_migrate}}"
  vars_files:
    - ['{{inventory_dir}}/secrets.yml', 'secrets/{{env}}.yml']
  roles:
    - cassandra-deploy
